version: "3.9"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.3.0
    container_name: rampay-dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: rampay-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: rampay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: rampay-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

  payment-service:
    build:
      context: ../services/payment-service
      dockerfile: Dockerfile
    container_name: rampay-payment-service
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      DYNAMODB_LOCAL: "true"
      DYNAMODB_TABLE_PAYMENTS: Payments
      DYNAMODB_TABLE_OUTBOX: PaymentOutbox
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8080
    depends_on:
      dynamodb-local:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started

volumes:
  dynamodata:
